[package]
name = "truenas-shell-dns-auth"
version = "0.1.0"
edition = "2024"

[dependencies]
addr = "0.15.6"
base64-url = "3.0.0"
fern = "0.7.1"
humantime = "2.2.0"
log = "0.4.27"
thiserror = "2.0.12"
